src/AppBundle/Entity/Book.php
<?php
/**
 * Created by PhpStorm.
 * User: farmatholin
 * Date: 24.08.17
 * Time: 15:18
 */

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Book
 * @package AppBundle\Entity
 *
 * @ORM\Entity(repositoryClass="AppBundle\Entity\Repository\BookRepository")
 * @ORM\Table(name="book")
 *
 * @UniqueEntity(
 *     fields={"ISBN"},
 *     message="Такая книга уже есть"
 * )
 *
 * @UniqueEntity(
 *     fields={"name", "year"},
 *     message="Такая книга уже есть",
 *     errorPath="name",
 * )
 */
class Book
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    protected $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    protected $year;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     */
    protected $ISBN;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    protected $pages;


    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="books")
     * @ORM\JoinColumn(name="owner_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $owner;
    /**
     * @var ArrayCollection
     * @ORM\ManyToMany(targetEntity="Author", mappedBy="books", cascade={"persist", "remove"})
     */
    protected $authors;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     *
     */
    protected $imagePath;

    /**
     * @var UploadedFile
     *
     * @Assert\File(
     *     mimeTypes={"image/jpeg", "image/pjpeg", "image/png", "image/x-png"}
     * )
     */
    protected $imageFile;


    public function __construct()
    {
        $this->authors = new ArrayCollection();
    }

    /**HeadooUserBundle:User
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * @param mixed $year
     * @return $this
     */
    public function setYear($year)
    {
        $this->year = $year;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getISBN()
    {
        return $this->ISBN;
    }

    /**
     * @param mixed $ISBN
     * @return $this
     */
    public function setISBN($ISBN)
    {
        $this->ISBN = $ISBN;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPages()
    {
        return $this->pages;
    }

    /**
     * @param mixed $pages
     * @return $this
     */
    public function setPages($pages)
    {
        $this->pages = $pages;
        return $this;
    }

    /**
     * @return User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param User $owner
     * @return $this
     */
    public function setOwner($owner)
    {
        $this->owner = $owner;
        return $this;
    }

    /**
     * @return string
     */
    public function getImagePath()
    {
        return $this->imagePath;
    }

    /**
     * @param string $imagePath
     * @return $this
     */
    public function setImagePath($imagePath)
    {
        $this->imagePath = $imagePath;
        return $this;
    }


    /**
     * @param Author $author
     * @return $this
     */
    public function addAuthor(Author $author)
    {
        $this->authors->add($author);
        $author->addBook($this);

        return $this;
    }

    /**
     * @param Author $author
     * @return $this
     */
    public function removeAuthor(Author $author)
    {
        $this->authors->removeElement($author);
        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param UploadedFile $imageFile
     */
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
    }

    /**
     * Get rooms
     *
     * @return \Doctrine\Common\Collections\Collection | Author[]
     */
    public function getAuthors()
    {
        return $this->authors;
    }

    public function getDataForSelect()
    {
        return [
            'id' => $this->getId(),
            'text' => $this->getName()
        ];
    }

}

src/AppBundle/Form/Type/BookType.php
<?php
/**
 * Created by PhpStorm.
 * User: farmatholin
 * Date: 25.08.17
 * Time: 2:48
 */

namespace AppBundle\Form\Type;


use AppBundle\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Tetranz\Select2EntityBundle\Form\Type\Select2EntityType;

/**
 * Class BookType
 * @package AppBundle\Form\Type
 */
class BookType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('name', null, [
            'label' => 'Название книги'
        ])->add('year', null, [
            'label' => 'Год выпуска',
        ])->add('ISBN', null, [
            'label' => 'ISBN'
        ])->add('pages', null, [
            'label' => 'кол-во страниц'
        ]);

        $builder->add('imageFile', FileType::class, [
            'required' => false,
        ]);

        $builder->add('authors', Select2EntityType::class, [
            'multiple' => true,
            'remote_route' => 'authors_select',
            'class' => Author::class,
            'primary_key' => 'id',
            'text_property' => 'fio',
            'minimum_input_length' => 0,
            'page_limit' => 10,
            'allow_clear' => true,
            'placeholder' => 'Выберете Автора',
        ]);
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'AppBundle\Entity\Book'
            ]
        );
    }

    public function getName()
    {
        return "book_type";
    }
}

src/AppBundle/Controller/BookController.php
<?php
/**
 * Created by PhpStorm.
 * User: farmatholin
 * Date: 25.08.17
 * Time: 1:07
 */

namespace AppBundle\Controller;


use AppBundle\Entity\Book;
use AppBundle\Form\Type\BookType;
use Doctrine\ORM\EntityManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

/**
 * Class BookController
 * @package AppBundle\Controller
 *
 * @Route("/book")
 */
class BookController extends Controller
{

    /**
     * @Route("/", name="book_index")
     * @Template()
     * @param Request $request
     * @return array
     */
    public function indexAction(Request $request){

        $em = $this->getDoctrine()->getManager();
        $books = $em->getRepository("AppBundle:Book")->getAllBooks();

        $paginator = $this->get('knp_paginator')->paginate($books, $request->query->get('page', 1), 20);

        return [
            'paginator' => $paginator,
        ];
    }

    /**
     * @Route("/view/{id}", name="book_view")
     * @Template()
     * @param Request $request
     * @param Book $book
     * @return array
     */
    public function viewAction(Request $request, Book $book){

        return [
            'book' => $book
        ];
    }

    /**
     * @Route("/new", name="book_new")
     * @Template()
     * @Security(expression="is_granted('IS_AUTHENTICATED_REMEMBERED')")
     * @param Request $request
     * @return array
     */
    public function newBookAction(Request $request) {

        $book = new Book();
        $form = $this->createForm(BookType::class, $book);

        return [
            'form' => $form->createView(),
            'book' => $book,
        ];
    }

    /**
     * @Route("/create", name="book_create")
     * @Method("POST")
     * @Template("AppBundle:Book:newBook.html.twig")
     * @Security(expression="is_granted('IS_AUTHENTICATED_REMEMBERED')")
     *
     * @param Request $request
     * @return array|RedirectResponse
     */
    public function createBookAction(Request $request){
        $book = new Book();
        $form = $this->createForm(BookType::class, $book);

        $form->handleRequest($request);
        if($form->isValid()){

            $em = $this->getDoctrine()->getManager();
            $book->setOwner($this->getUser());

            $em->persist($book);

            $em->flush();

            return $this->redirect($this->generateUrl('book_index'));
        }

        return [
            'form' => $form->createView(),
            'book' => $book,
        ];
    }

    /**
     * @Route("/edit/{id}", name="book_edit")
     * @Template()
     * @Security(expression="user.canEditBook(book)")
     *
     * @param Request $request
     * @param Book $book
     * @return array
     */
    public function editBookAction(Request $request, Book $book) {

        $form = $this->createForm(BookType::class, $book);

        return [
            'form' => $form->createView(),
            'book' => $book,
        ];
    }

    /**
     * @Route("/update/{id}", name="book_update")
     * @Template("@App/Book/editBook.html.twig")
     * @Security(expression="user.canEditBook(book)")
     *
     * @param Request $request
     * @param Book $book
     * @return array|RedirectResponse
     */
    public function updateBookAction(Request $request, Book $book){
        $form = $this->createForm(BookType::class, $book);

        $form->handleRequest($request);
        if($form->isValid()){

            $em = $this->getDoctrine()
                ->getManager();

            // Remove old file if we upload new
            if($book->getImageFile() instanceof UploadedFile){
                $this->get('app.util.file_uploader')
                    ->remove($book->getImagePath());
            }

            $em->persist($book);

            $em->flush();

            return $this->redirect($this->generateUrl('book_index'));
        }

        return [
            'form' => $form->createView(),
            'book' => $book,
        ];
    }

    /**
     * @Route("/remove/{id}", name="book_remove")
     * @Security(expression="user.canEditBook(book)")
     * @param Request $request
     * @param Book $book
     * @return RedirectResponse
     */
    public function removeBookAction(Request $request, Book $book){
        $em = $this->getDoctrine()->getManager();

        $em->remove($book);
        $em->flush();

        return $this->redirect($this->generateUrl('book_index'));

    }

    /**
     * @Route("/_book_select", name="books_select")
     *
     * @param Request $request
     *
     * @return JsonResponse
     */
    public function getAllBooksSelectAction(Request $request){

        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();

        $booksRaw = $em->getRepository("AppBundle:Book")->getAllBooks();

        $books = [];

        /** @var Book $book */
        foreach ($booksRaw as $book){
            $books[] = $book->getDataForSelect();
        }

        return new JsonResponse([
            'results' => $books,
            'more' => true,
        ]);
    }
}

src/AppBundle/Resources/views/Book/editBook.html.twig
{% extends '@App/layout.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {{ form_start(form, {action: path('book_update', {id: book.id}), attr: {'class': 'horizontal'}}) }}
            {{ form_widget(form) }}
            <div class="btn-footer">
                <button class="btn btn-default btn-lg" type="submit">&nbsp;Save</button>
            </div>
            {{ form_end(form) }}
        </div>
        <div class="col-md-4">
            {% if book.imagePath != null %}
                <img class="book-image" src="{{ asset("uploads/books_image/" ~ book.imagePath) }}" alt="{{ book.name }}">
            {% else %}
                <img src="{{ asset('bundles/app/img/no_image.png') }}" alt="no_image"/>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Book/index.html.twig
{% extends '@App/layout.html.twig' %}

{% block content %}
    <div>
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <div class="pull-right">
                <a href="{{ path('book_new') }}" class="btn btn-warning">Добавить Книгу</a>
            </div>
        {% endif %}
    </div>
    <table class="table">
        <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Год
            </th>
            <th>
                ISBN
            </th>
            <th>
                Страниц
            </th>
            <th>
                Действия
            </th>
        </tr>
        </thead>
        <tbody>
        {% for book in paginator %}
            <tr>
                <td>
                    {{ book.name }}
                </td>
                <td>
                    {{ book.year }}
                </td>
                <td>
                    {{ book.ISBN }}
                </td>
                <td>
                    {{ book.pages }}
                </td>

                <td>
                    <a class="btn btn-success" href="{{ path('book_view', {id:book.id}) }}">Просмотр</a>
                    {% if app.user == book.owner %}
                        <a href="{{ path('book_edit', {id:book.id}) }}" class="btn btn-warning">Редактировать</a>
                        <a href="{{ path('book_remove', {id:book.id}) }}" class="btn btn-error">Удалить</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if paginator is empty %}
        <div>Нет Книг</div>
    {% endif %}
    <div class="pull-right">
        {{ knp_pagination_render(paginator) }}
    </div>
{% endblock content %}

src/AppBundle/Resources/views/Book/newBook.html.twig
{% extends '@App/layout.html.twig' %}

{% block content %}
    {{ form_start(form, {action: path('book_create', {id: book.id}), attr: {'class': 'horizontal'}}) }}
    {{ form_widget(form) }}
    <div class="btn-footer">
        <button class="btn btn-default btn-lg" type="submit">&nbsp;Save</button>
    </div>
    {{ form_end(form) }}
{% endblock content %}

src/AppBundle/Resources/views/Book/view.html.twig
{% extends '@App/layout.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            {% if book.imagePath != null %}
                <img class="book-image" src="{{ asset("uploads/books_image/" ~ book.imagePath) }}" alt="{{ book.name }}">
            {% else %}
                <img class="book-image" src="{{ asset('bundles/app/img/no_image.png') }}" alt="no_image"/>
            {% endif %}
            <div>
                {% if app.user == book.owner %}
                    <a href="{{ path('book_edit', {id:book.id}) }}" class="btn btn-warning">Редактировать</a>
                    <a href="{{ path('book_remove', {id:book.id}) }}" class="btn btn-error">Удалить</a>
                {% endif %}
            </div>
        </div>
        <div class="col-md-8">
            <div>
                <b>Название: </b>
                {{ book.name }}
            </div>
            <div>
                <b>Год: </b>
                {{ book.year }}
            </div>
            <div>
                <b>ISNB: </b>
                {{ book.iSBN }}
            </div>
            <div>
                <b>Страниц: </b>
                {{ book.pages }}
            </div>
            <hr/>
            {% if book.authors|length > 0 %}
                <div>
                    <b>Автор(ы): </b>
                    {% for author in book.authors %}
                        <p>
                            <a href="{{ path('author_view',{id:author.id}) }}">{{ author.fioFormatted }}</a>
                        </p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

    </div>
{% endblock %}